export type Testimonial = {
  quote: string;
  imgName: string;
  userName: string;
  userDesignation: string;
};

export type TestimonialProps = {
  testimonials: Testimonial[];
};

export type Expert = {
  name: string;
  designation: string;
  imgName: string;
};

export type ExpertsProps = {
  experts: Expert[];
};

export type BookingForm = {
  fromDate: string;
  toDate: string;
  fullName: string;
  email: string;
  phoneNumber: string;
  serviceType: string;
  pickupLocation: string;
  carType: string;
  carBrand: string;
  carModel: string;
};

export const CarTypes = {
  Electric: "Electric",
  Luxury: "Luxury",
  Sedan: "Sedan",
  Sports: "Sports",
  SUV: "SUV",
} as const;

export type CarTypes = (typeof CarTypes)[keyof typeof CarTypes];

export type OptionType = {
  label: string;
  value: string;
};

export type BookingOrderResponse = {
  orderId: string;
  amount: number;
  currency: string;
  success: boolean;
  statusCode: number;
  message: string;
};

export type BookingOrderPayload = {
  fromDate: string;
  toDate: string;
  fullName: string;
  email: string;
  phoneNumber: string;
  serviceType: string;
  serviceId: string;
  pickupLocation: string;
  carType: string;
  carId?: string;
  carBrand?: string;
  carModel?: string;
};

export type RazorpayPaymentResponse = {
  razorpay_order_id: string; // The order ID generated by your backend via Razorpay API
  razorpay_payment_id: string; // Unique ID for the payment generated by Razorpay
  razorpay_signature: string; // HMAC SHA256 signature for verification
};

export type VerifyServiceBookingPayload = RazorpayPaymentResponse;

export type VerifyServiceBookingResponse = {
  success: boolean;
  statusCode: number;
  message: string;
};

export type OptionTypeValue = OptionType & {
  isSelected: boolean
}

export type ActiveFilter = {
  category: string;
  label: string;
  value: string;
}

export type FilterList = {
    searchText: string;
    perDayRate: {
        min: string;
        max: string;
    };
    carBrand: OptionTypeValue[];
    carType: OptionTypeValue[];
    transmission: OptionTypeValue[];
    activeFilters: ActiveFilter[];
}
